/* MB360 · Resultados v2 · 2026-08 */
(() => {
  const R={view:'dashboard',clientId:'',period:'30d',locationId:'',mode:'internal',data:null,metricKey:'sales',customStart:'',customEnd:'',importRows:[],importFile:null};
  const $=id=>document.getElementById(id);
  const safe=v=>typeof esc==='function'?esc(v):String(v??'');
  const resultTimezone=()=>R.data?.settings?.timezone||'America/New_York';
  const datePartsInZone=(value=new Date())=>{try{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:resultTimezone(),year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(value instanceof Date?value:new Date(value)),o={};parts.forEach(p=>{if(p.type!=='literal')o[p.type]=p.value;});return{year:o.year,month:o.month,day:o.day};}catch(e){const d=value instanceof Date?value:new Date(value);return{year:String(d.getFullYear()),month:String(d.getMonth()+1).padStart(2,'0'),day:String(d.getDate()).padStart(2,'0')};}};
  const dateInZone=value=>{if(!value)return'';const p=datePartsInZone(value);return`${p.year}-${p.month}-${p.day}`;};
  const today=()=>dateInZone(new Date());
  const addDays=(s,n)=>{const d=new Date((s||today())+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`;};
  const daysBetween=(a,b)=>Math.max(1,Math.round((new Date(b+'T12:00:00Z')-new Date(a+'T12:00:00Z'))/86400000)+1);
  const num=v=>Number(v||0);
  const pct=v=>Number.isFinite(v)?`${v>=0?'+':''}${v.toFixed(1)}%`:'—';
  const money=(v,c='USD')=>Number(v||0).toLocaleString('en-US',{style:'currency',currency:c,maximumFractionDigits:0});
  const qty=v=>Number(v||0).toLocaleString('en-US',{maximumFractionDigits:1});
  const fmtDate=v=>{if(!v)return'—';const d=new Date(v.length===10?v+'T12:00:00Z':v);return Number.isNaN(d)?v:d.toLocaleDateString('es-US',{day:'numeric',month:'short',year:'numeric',timeZone:resultTimezone()});};
  const MET={sales:{label:'Ventas',unit:'currency',agg:'sum'},avg_ticket:{label:'Ticket promedio',unit:'currency',agg:'avg'},customers:{label:'Clientes',unit:'number',agg:'sum'},direct_orders:{label:'Pedidos directos',unit:'number',agg:'sum'},google_reviews_new:{label:'Reseñas Google',unit:'number',agg:'sum'},google_actions:{label:'Acciones Google Maps',unit:'number',agg:'sum'},leads:{label:'Leads / mensajes',unit:'number',agg:'sum'},reservations:{label:'Reservas',unit:'number',agg:'sum'},google_views:{label:'Visualizaciones Google',unit:'number',agg:'sum'},google_directions:{label:'Indicaciones',unit:'number',agg:'sum'},google_calls:{label:'Llamadas',unit:'number',agg:'sum'},website_clicks:{label:'Clics web',unit:'number',agg:'sum'},menu_clicks:{label:'Clics al menú',unit:'number',agg:'sum'},impressions:{label:'Impresiones',unit:'number',agg:'sum'},clicks:{label:'Clics',unit:'number',agg:'sum'},reach:{label:'Alcance',unit:'number',agg:'sum'},views:{label:'Reproducciones',unit:'number',agg:'sum'},engagements:{label:'Interacciones',unit:'number',agg:'sum'},orders:{label:'Pedidos',unit:'number',agg:'sum'},attributed_sales:{label:'Ventas atribuibles',unit:'currency',agg:'sum'},ad_spend:{label:'Gasto publicidad',unit:'currency',agg:'sum'},promo_cost:{label:'Costo promociones',unit:'currency',agg:'sum'},gross_profit:{label:'Ganancia',unit:'currency',agg:'sum'},new_customers:{label:'Clientes nuevos',unit:'number',agg:'sum'},returning_customers:{label:'Clientes recurrentes',unit:'number',agg:'sum'},cac:{label:'CAC',unit:'currency',agg:'avg'},ltv:{label:'LTV',unit:'currency',agg:'avg'},rating:{label:'Rating Google',unit:'number',agg:'latest'},review_count:{label:'Reseñas totales',unit:'number',agg:'latest'}};
  const channelLabel=v=>({google:'Google / Maps',instagram:'Instagram',facebook:'Facebook',tiktok:'TikTok',web:'Web / SEO',whatsapp:'WhatsApp',orders:'Pedidos / Reservas',pos:'POS / Ventas',delivery:'Delivery',other:'Otro'})[v]||v||'Sin canal';
  const qualityLabel=v=>({verified:'✅ Verificado',estimated:'🟡 Estimado',client_reported:'🔵 Reportado',incomplete:'⚠️ Incompleto'})[v]||v||'Sin definir';
  const activeClient=()=>clientCache.find(c=>c.id===activeWorkspaceClientId)||null;
  const clientName=id=>clientCache.find(c=>c.id===id)?.business_name||'Cliente';
  function periodRange(){const end=today();if(R.period==='custom'&&R.customStart&&R.customEnd)return{start:R.customStart,end:R.customEnd};const d=R.period==='7d'?7:R.period==='90d'?90:R.period==='6m'?183:R.period==='1y'?365:30;return{start:addDays(end,-d+1),end};}
  function previousRange(){const p=periodRange(),n=daysBetween(p.start,p.end);return{start:addDays(p.start,-n),end:addDays(p.start,-1)};}
  function valFormat(key,v,currency='USD'){const m=MET[key]||{};return m.unit==='currency'?money(v,currency):qty(v);}
  function metricName(k){return MET[k]?.label||String(k||'').replaceAll('_',' ');}

  /*
   * Canonical metric aggregation.
   * A metric can arrive daily, weekly and monthly at the same time. Summing every
   * overlapping row would count the same business result more than once. We first
   * keep only rows fully contained in the requested period, prefer explicit rollups
   * over dimensional breakdowns when both coexist, and then choose one source + one
   * granularity for each metric series based on coverage, data quality and freshness.
   */
  const QUALITY_RANK={verified:4,client_reported:3,estimated:2,incomplete:1};
  const METRIC_DIMS=['location_id','channel','product_id','campaign_id','content_item_id','publication_id','customer_segment_id','time_slot_id'];
  function metricSpan(x){return daysBetween(x.period_start,x.period_end);}
  function collectionFrequency(start,end){const d=daysBetween(start,end);return d<=1?'daily':d<=8?'weekly':d<=35?'monthly':d<=100?'quarterly':'annual';}
  function rowFreshness(x){return Date.parse(x.last_synced_at||x.updated_at||x.created_at||x.period_end||'1970-01-01')||0;}
  function exactDedupe(rows){const best=new Map();for(const x of rows){const k=[x.period_start,x.period_end,x.source||'',...METRIC_DIMS.map(f=>x[f]||'')].join('|'),old=best.get(k);if(!old||(QUALITY_RANK[x.data_quality]||0)>(QUALITY_RANK[old.data_quality]||0)||((QUALITY_RANK[x.data_quality]||0)===(QUALITY_RANK[old.data_quality]||0)&&rowFreshness(x)>rowFreshness(old)))best.set(k,x);}return[...best.values()];}
  function coverageDays(rows){const a=rows.map(x=>[x.period_start,x.period_end]).sort((x,y)=>x[0].localeCompare(y[0]));if(!a.length)return 0;let total=0,s=a[0][0],e=a[0][1];for(let i=1;i<a.length;i++){const [ns,ne]=a[i];if(ns<=addDays(e,1)){if(ne>e)e=ne;}else{total+=daysBetween(s,e);s=ns;e=ne;}}return total+daysBetween(s,e);}
  function preferRollups(rows){let out=rows.slice();for(const f of METRIC_DIMS){const hasRollup=out.some(x=>!x[f]),hasDetail=out.some(x=>!!x[f]);if(hasRollup&&hasDetail)out=out.filter(x=>!x[f]);}return out;}
  function canonicalMetricRows(rows,key){let a=rows.filter(x=>x.metric_key===key);if(!a.length)return[];a=preferRollups(a);const kind=MET[key]?.agg||'sum';if(kind==='latest')return exactDedupe(a).sort((x,y)=>(y.period_end||'').localeCompare(x.period_end||'')||rowFreshness(y)-rowFreshness(x)).slice(0,1);
    const series=new Map();for(const x of a){const sk=METRIC_DIMS.map(f=>x[f]||'').join('|');(series.get(sk)||series.set(sk,[]).get(sk)).push(x);}const chosen=[];
    for(const group of series.values()){
      const candidates=new Map();for(const x of group){const span=metricSpan(x),freq=x.collection_frequency||collectionFrequency(x.period_start,x.period_end),ck=`${x.source||'Sin fuente'}|${freq}|${span}`;(candidates.get(ck)||candidates.set(ck,[]).get(ck)).push(x);}let best=null;
      for(const raw of candidates.values()){const rs=exactDedupe(raw),coverage=coverageDays(rs),quality=rs.reduce((s,x)=>s+(QUALITY_RANK[x.data_quality]||0),0)/Math.max(1,rs.length),span=rs.reduce((s,x)=>s+metricSpan(x),0)/Math.max(1,rs.length),fresh=Math.max(...rs.map(rowFreshness));const score={rows:rs,coverage,quality,span,fresh};if(!best||score.coverage>best.coverage||(score.coverage===best.coverage&&score.quality>best.quality)||(score.coverage===best.coverage&&score.quality===best.quality&&((kind==='avg'&&score.span>best.span)||(kind!=='avg'&&score.span<best.span)))||(score.coverage===best.coverage&&score.quality===best.quality&&score.span===best.span&&score.fresh>best.fresh))best=score;}
      if(best)chosen.push(...best.rows);
    }
    return chosen;
  }
  function aggregate(rows,key){const a=canonicalMetricRows(rows,key);if(!a.length)return null;const kind=MET[key]?.agg||'sum';if(kind==='latest')return num(a[0].metric_value);if(kind==='avg')return a.reduce((s,x)=>s+num(x.metric_value),0)/a.length;return a.reduce((s,x)=>s+num(x.metric_value),0);}
  function change(cur,prev){if(cur==null||prev==null||prev===0)return null;return ((cur-prev)/Math.abs(prev))*100;}
  function inRange(x,p){return x.period_start<=p.end&&x.period_end>=p.start;}
  function metricInRange(x,p){const kind=MET[x.metric_key]?.agg||'sum';if(kind==='latest')return x.period_end>=p.start&&x.period_end<=p.end;return x.period_start>=p.start&&x.period_end<=p.end;}
  function rowsFor(p,d=R.data){return(d?.metrics||[]).filter(x=>metricInRange(x,p)&&(!R.locationId||x.location_id===R.locationId));}
  function trendClass(v){return v==null?'res2-flat':v>1?'res2-up':v<-1?'res2-down':'res2-flat';}
  function trendArrow(v){return v==null?'Sin comparación':v>1?`↑ ${pct(v)}`:v<-1?`↓ ${pct(Math.abs(v))}`:`→ ${pct(v)}`;}

  async function ensure(){await loadClients();R.clientId=activeWorkspaceClientId&&clientCache.some(c=>c.id===activeWorkspaceClientId)?activeWorkspaceClientId:'';}
  async function fetchAllMetrics(cid){const pageSize=1000,all=[];for(let from=0;;from+=pageSize){const{data,error}=await sb.from('metrics').select('*').eq('client_id',cid).order('period_end',{ascending:false}).range(from,from+pageSize-1);if(error)return{data:null,error};const rows=data||[];all.push(...rows);if(rows.length<pageSize)break;}return{data:all,error:null};}
  async function loadData(){if(!R.clientId){R.data=null;return null;}const cid=R.clientId;const qs=await Promise.all([
    fetchAllMetrics(cid),
    sb.from('metric_targets').select('*').eq('client_id',cid).order('target_date',{ascending:false}),
    sb.from('locations').select('*').eq('client_id',cid).eq('active',true).order('is_primary',{ascending:false}),
    sb.from('products').select('*').eq('client_id',cid).eq('active',true),
    sb.from('campaigns').select('*').eq('client_id',cid).order('created_at',{ascending:false}),
    sb.from('content_items').select('*,publications(*)').eq('client_id',cid).order('created_at',{ascending:false}),
    sb.from('activities').select('*').eq('client_id',cid).order('performed_at',{ascending:false}).limit(300),
    sb.from('tasks').select('id,title,status,completed_at,created_at,task_type,origin,expected_profit_impact,completion_result').eq('client_id',cid).order('created_at',{ascending:false}).limit(300),
    sb.from('result_attributions').select('*').eq('client_id',cid).order('created_at',{ascending:false}).limit(500),
    sb.from('result_experiments').select('*').eq('client_id',cid).order('created_at',{ascending:false}),
    sb.from('competitors').select('*').eq('client_id',cid).eq('active',true),
    sb.from('competitor_metrics').select('*').eq('client_id',cid).order('period_end',{ascending:false}).limit(1000),
    sb.from('client_systems').select('*').eq('client_id',cid).order('system_name'),
    sb.from('commercial_calendar').select('*').eq('client_id',cid).order('start_date',{ascending:false}).limit(200),
    sb.from('customer_segments').select('*').eq('client_id',cid),
    sb.from('business_time_slots').select('*').eq('client_id',cid),
    sb.from('result_imports').select('*').eq('client_id',cid).order('created_at',{ascending:false}).limit(50),
    sb.from('result_settings').select('*').eq('client_id',cid).limit(1)
  ]);const e=qs.find(x=>x.error)?.error;if(e)throw e;R.data={metrics:qs[0].data||[],targets:qs[1].data||[],locations:qs[2].data||[],products:qs[3].data||[],campaigns:qs[4].data||[],content:qs[5].data||[],activities:qs[6].data||[],tasks:qs[7].data||[],attributions:qs[8].data||[],experiments:qs[9].data||[],competitors:qs[10].data||[],competitorMetrics:qs[11].data||[],systems:qs[12].data||[],calendar:qs[13].data||[],segments:qs[14].data||[],slots:qs[15].data||[],imports:qs[16].data||[],settings:qs[17].data?.[0]||null};return R.data;}

  function nav(){const a=[['dashboard','Resumen'],['channels','Canales'],['products','Productos'],['campaigns','Campañas'],['trends','Tendencias'],['attribution','Impacto'],['experiments','Pruebas'],['data','Datos'],['ask','Preguntar'],['client','Vista cliente']];return `<div class="res2-tabs">${a.map(([id,l])=>`<button class="${R.view===id?'active':''}" onclick="res2Go('${id}')">${l}</button>`).join('')}</div>`;}
  function periods(){return `<div class="res2-periods">${[['7d','7 días'],['30d','30 días'],['90d','90 días'],['6m','6 meses'],['1y','1 año'],['custom','Personalizado']].map(([v,l])=>`<button class="${R.period===v?'active':''}" onclick="res2Period('${v}')">${l}</button>`).join('')}</div>${R.period==='custom'?`<div class="res2-filterbar"><input id="res2Start" type="date" value="${R.customStart}"><input id="res2End" type="date" value="${R.customEnd}"><button class="btn primary" onclick="res2ApplyCustom()">Aplicar</button></div>`:''}`;}
  function locationFilter(){const locs=R.data?.locations||[];return `<div class="res2-filterbar"><select onchange="res2Location(this.value)"><option value="">Todas las ubicaciones</option>${locs.map(x=>`<option value="${x.id}" ${R.locationId===x.id?'selected':''}>${safe(x.location_name||x.address||'Ubicación')}</option>`).join('')}</select><div></div></div>`;}
  function shell(body,title='📈 Resultados',hint='Mide qué está funcionando y cuánto valor está generando MB360.'){const c=activeClient(),loc=c?clientMainLocation(c):null;const banner=activeClientBannerMarkup('res2Active',c?.business_name||'',loc?.address||'','Selecciona un cliente para ver resultados');return pageHead('Medición',title,hint,'<button class="btn ghost" onclick="openTool(\'home\')">← Inicio</button>')+banner+periods()+locationFilter()+nav()+`<div class="res2 ${R.mode==='client'?'res2-clientmode':''}">${body}</div>`;}
  function chooser(){return `<div class="card"><div class="section-title">Selecciona un cliente</div><select onchange="res2SelectClient(this.value)">${clientOptions(activeWorkspaceClientId)}</select></div>`;}

  function targetFor(key){return(R.data.targets||[]).find(x=>x.metric_key===key&&(!R.locationId||x.location_id===R.locationId))||null;}
  function kpi(key,curRows,prevRows){const cur=aggregate(curRows,key),prev=aggregate(prevRows,key),ch=change(cur,prev),t=targetFor(key),currency=R.data.settings?.currency||'USD';const progress=t?.target_value&&cur!=null?Math.max(0,Math.min(100,cur/num(t.target_value)*100)):null;return `<div class="res2-kpi"><span>${safe(metricName(key))}</span><b>${cur==null?'Sin datos':valFormat(key,cur,currency)}</b><small class="${trendClass(ch)}">${trendArrow(ch)}</small>${progress!=null?`<div class="res2-goal"><i style="width:${progress}%"></i></div><div class="res2-goal-note">Meta ${valFormat(key,t.target_value,currency)} · ${progress.toFixed(0)}%</div>`:''}</div>`;}
  function insights(cur,prev){const keys=['sales','direct_orders','google_actions','leads','reservations'];const out=[];for(const k of keys){const a=aggregate(cur,k),b=aggregate(prev,k),c=change(a,b);if(c==null)continue;if(c<=-10)out.push({level:'high',title:`${metricName(k)} bajó ${Math.abs(c).toFixed(1)}%`,detail:'Conviene revisar canal, oferta, conversión y acciones recientes.',key:k});else if(c>=15)out.push({level:'good',title:`${metricName(k)} mejoró ${c.toFixed(1)}%`,detail:'Revisa qué acciones coincidieron con esta mejora para decidir si conviene repetirlas.',key:k});}
    const reach=aggregate(cur,'reach'),orders=aggregate(cur,'direct_orders')||aggregate(cur,'orders');if(reach>1000&&orders!=null&&orders<10)out.push({level:'medium',title:'Mucho alcance y poca conversión',detail:'El contenido genera atención, pero los pedidos atribuibles son bajos.',key:'reach'});
    const clicks=aggregate(cur,'menu_clicks')||aggregate(cur,'website_clicks');if(clicks>100&&orders!=null&&orders/clicks<.05)out.push({level:'high',title:'Muchos clics y pocos pedidos',detail:'Revisar menú, precio, oferta o fricción del proceso de compra.',key:'direct_orders'});return out.slice(0,8);}
  function dashboard(){const cur=rowsFor(periodRange()),prev=rowsFor(previousRange()),ins=insights(cur,prev),currency=R.data.settings?.currency||'USD';const p=periodRange();const sales=aggregate(cur,'sales'),target=targetFor('sales');const proj=projectionSales();return `<div class="res2-kpis">${['sales','avg_ticket','customers','direct_orders','google_reviews_new','google_actions','leads','reservations'].map(k=>kpi(k,cur,prev)).join('')}</div><div class="res2-actions"><button class="btn primary" onclick="res2Go('record')">+ Registrar resultado</button><button class="btn ghost" onclick="res2GenerateReport()">Generar reporte</button></div>${proj?`<div class="res2-proj"><small>Proyección de cierre · ${safe(proj.label)}</small><b>${money(proj.projected,currency)}</b><small>${target?.target_value?`Meta ${money(target.target_value,currency)} · ${proj.projected>=target.target_value?'🟢 En camino':'🟡 Riesgo de no llegar'}`:'Basada en el ritmo actual del período.'}</small></div>`:''}${ins.length?`<div class="card"><div class="res2-section-title"><b>Alertas e interpretación</b></div>${ins.map(x=>`<div class="res2-alert ${x.level}"><b>${x.level==='good'?'🟢':'⚠️'} ${safe(x.title)}</b><small>${safe(x.detail)}</small><button class="mini-btn" onclick="res2CreateTask('${safe(x.title)}','${safe(x.detail)}')">Crear tarea</button></div>`).join('')}</div>`:''}<div class="card"><div class="res2-section-title"><b>Embudo de conversión</b></div>${funnel(cur)}</div><div class="card"><div class="res2-section-title"><b>Antes vs ahora</b></div>${beforeAfter(cur)}</div><div class="card internal-only"><div class="res2-section-title"><b>Rentabilidad MB360</b></div>${roi(cur)}</div><div class="card"><div class="res2-section-title"><b>Acciones con mayor impacto</b></div>${topActions()}</div><div class="card"><div class="res2-section-title"><b>Línea de tiempo del período</b></div>${timeline(p)}</div>`;}
  function projectionSales(){const cur=rowsFor(periodRange()),sales=aggregate(cur,'sales');if(sales==null)return null;const p=periodRange(),cutoff=p.end<today()?p.end:today(),elapsed=daysBetween(p.start,cutoff),total=daysBetween(p.start,p.end);return{projected:sales/Math.max(1,elapsed)*total,label:`${fmtDate(p.start)} – ${fmtDate(p.end)}`};}
  function funnel(cur){const a=[['Visualizaciones',aggregate(cur,'google_views')||aggregate(cur,'impressions')],['Acciones',aggregate(cur,'google_actions')],['Clics',aggregate(cur,'menu_clicks')||aggregate(cur,'website_clicks')||aggregate(cur,'clicks')],['Pedidos',aggregate(cur,'direct_orders')||aggregate(cur,'orders')],['Ventas',aggregate(cur,'sales')]];return `<div class="res2-funnel">${a.map((x,i)=>`<div class="res2-funnel-step"><b>${x[0]}</b><span>${x[1]==null?'Sin datos':x[0]==='Ventas'?money(x[1],R.data.settings?.currency||'USD'):qty(x[1])}${i&&a[i-1][1]&&x[1]!=null?` · ${(x[1]/a[i-1][1]*100).toFixed(1)}%`:''}</span></div>`).join('')}</div>`;}
  function beforeAfter(cur){const base=R.data.metrics.filter(x=>x.is_baseline&&(!R.locationId||x.location_id===R.locationId));const keys=['sales','direct_orders','review_count','avg_ticket'];return `<div class="res2-compare"><div><h4>Antes de MB360</h4>${keys.map(k=>`<div class="res2-row"><div><b>${metricName(k)}</b></div><div class="res2-value"><b>${aggregate(base,k)==null?'—':valFormat(k,aggregate(base,k),R.data.settings?.currency||'USD')}</b></div></div>`).join('')}</div><div><h4>Período actual</h4>${keys.map(k=>`<div class="res2-row"><div><b>${metricName(k)}</b></div><div class="res2-value"><b>${aggregate(cur,k)==null?'—':valFormat(k,aggregate(cur,k),R.data.settings?.currency||'USD')}</b></div></div>`).join('')}</div></div>`;}
  function roi(cur){const c=R.data.settings?.currency||'USD',rev=aggregate(cur,'attributed_sales'),profit=aggregate(cur,'gross_profit'),ads=aggregate(cur,'ad_spend'),promo=aggregate(cur,'promo_cost'),fee=num(R.data.settings?.mb360_monthly_fee);if(rev==null&&profit==null)return'<div class="empty">Faltan ventas atribuibles o ganancia para calcular rentabilidad.</div>';const benefit=profit!=null?profit:0,cost=num(ads)+num(promo)+fee,net=benefit-cost,ratio=cost>0?net/cost*100:null;return `<div class="res2-mini"><div><span>Ventas atribuibles</span><b>${rev==null?'—':money(rev,c)}</b></div><div><span>Ganancia estimada</span><b>${profit==null?'—':money(profit,c)}</b></div><div><span>Costos medidos</span><b>${money(cost,c)}</b></div><div><span>Retorno neto</span><b>${money(net,c)}</b></div><div><span>ROI</span><b>${ratio==null?'—':pct(ratio)}</b></div></div><p class="hint">Los cálculos respetan la calidad del dato; si faltan costos o márgenes, no se inventan.</p>`;}
  function topActions(){const a=(R.data.attributions||[]).slice().sort((x,y)=>num(y.attributed_profit||y.attributed_revenue||y.attributed_value)-num(x.attributed_profit||x.attributed_revenue||x.attributed_value)).slice(0,8);if(!a.length)return'<div class="empty">Todavía no hay atribuciones registradas.</div>';return a.map(x=>`<div class="res2-row"><div><b>${safe(x.source_type)}${x.notes?' · '+safe(x.notes):''}</b><small>${safe(x.attribution_method)} · confianza ${safe(x.confidence)}</small></div><div class="res2-value"><b>${x.attributed_revenue!=null?money(x.attributed_revenue,R.data.settings?.currency||'USD'):qty(x.attributed_value)}</b></div></div>`).join('');}
  function timeline(p){const ev=[];(R.data.activities||[]).filter(x=>dateInZone(x.performed_at)>=p.start&&dateInZone(x.performed_at)<=p.end).forEach(x=>ev.push({d:x.performed_at,t:x.description,s:x.area||x.platform||'Acción'}));(R.data.campaigns||[]).filter(x=>x.start_date&&x.start_date<=p.end&&(!x.end_date||x.end_date>=p.start)).forEach(x=>ev.push({d:x.start_date,t:`Campaña: ${x.name}`,s:x.objective||x.offer||''}));(R.data.content||[]).flatMap(x=>(x.publications||[]).map(pu=>({d:pu.published_at,t:`Publicación: ${x.title||x.content_type}`,s:pu.platform}))).filter(x=>x.d&&dateInZone(x.d)>=p.start&&dateInZone(x.d)<=p.end).forEach(x=>ev.push(x));ev.sort((a,b)=>new Date(b.d)-new Date(a.d));return ev.length?`<div class="res2-timeline">${ev.slice(0,20).map(x=>`<div class="res2-event"><b>${fmtDate(x.d)} · ${safe(x.t)}</b><small>${safe(x.s)}</small></div>`).join('')}</div>`:'<div class="empty">No hay acciones registradas en este período.</div>';}

  function channels(){const cur=rowsFor(periodRange()),map={};cur.forEach(x=>{const c=x.channel||inferChannel(x.source);(map[c]??=[]).push(x);});const desired=['google','instagram','facebook','tiktok','web','whatsapp','orders','pos','delivery'];return `<div class="res2-grid">${desired.filter(c=>map[c]?.length).map(c=>`<div class="res2-channel"><h3>${safe(channelLabel(c))}</h3><div class="res2-mini">${topMetrics(map[c]).map(([k,v])=>`<div><span>${safe(metricName(k))}</span><b>${valFormat(k,v,R.data.settings?.currency||'USD')}</b></div>`).join('')}</div></div>`).join('')||'<div class="card empty">Todavía no hay métricas por canal.</div>'}</div>`;}
  function inferChannel(src){const s=String(src||'').toLowerCase();if(s.includes('google')||s.includes('gbp')||s.includes('maps'))return'google';if(s.includes('instagram'))return'instagram';if(s.includes('facebook')||s.includes('meta'))return'facebook';if(s.includes('tiktok'))return'tiktok';if(s.includes('whatsapp'))return'whatsapp';if(s.includes('pos'))return'pos';if(s.includes('web')||s.includes('search')||s.includes('analytics'))return'web';if(s.includes('delivery'))return'delivery';return'other';}
  function topMetrics(rows){const keys=[...new Set(rows.map(x=>x.metric_key))];return keys.map(k=>[k,aggregate(rows,k)]).filter(x=>x[1]!=null).slice(0,9);}

  function products(){const cur=rowsFor(periodRange());const rows=R.data.products.map(p=>{const m=cur.filter(x=>x.product_id===p.id);return{p,sales:aggregate(m,'sales')||aggregate(m,'attributed_sales'),orders:aggregate(m,'orders')||aggregate(m,'direct_orders'),reach:aggregate(m,'reach')||aggregate(m,'views')};}).sort((a,b)=>num(b.sales)-num(a.sales));return `<div class="card"><div class="res2-section-title"><b>Resultado por producto / plato</b></div>${rows.length?rows.map(x=>`<div class="res2-row"><div><b>${safe(x.p.name)}</b><small>${safe(x.p.profitability_level||'Margen sin definir')} · ${x.p.client_wants_to_push?'Producto prioritario':'Producto activo'}</small></div><div class="res2-value"><b>${x.sales!=null?money(x.sales,R.data.settings?.currency||'USD'):'Sin ventas'}</b><small>${x.orders!=null?`${qty(x.orders)} pedidos`:x.reach!=null?`${qty(x.reach)} alcance`:'Sin métricas'}</small></div></div>`).join(''):'<div class="empty">No hay productos cargados.</div>'}</div>`;}
  function campaigns(){const cur=rowsFor(periodRange());return `<div class="card"><div class="res2-section-title"><b>Campañas y promociones</b></div>${R.data.campaigns.length?R.data.campaigns.map(c=>{const m=cur.filter(x=>x.campaign_id===c.id),rev=aggregate(m,'attributed_sales')||aggregate(m,'sales'),profit=aggregate(m,'gross_profit'),spend=aggregate(m,'ad_spend')??c.budget,roi=profit!=null&&spend?((profit-spend)/spend*100):null;return `<div class="res2-row"><div><b>${safe(c.name)}</b><small>${safe(c.campaign_type)} · ${fmtDate(c.start_date)}${c.end_date?'–'+fmtDate(c.end_date):''}</small></div><div class="res2-value"><b>${rev!=null?money(rev,R.data.settings?.currency||'USD'):'Sin atribución'}</b><small>${roi!=null?`ROI ${pct(roi)}`:safe(c.status)}</small></div></div>`;}).join(''):'<div class="empty">Todavía no hay campañas.</div>'}</div>`;}

  function trends(){const keys=[...new Set(R.data.metrics.map(x=>x.metric_key))].sort();const rows=rowsFor(periodRange()).filter(x=>x.metric_key===R.metricKey).sort((a,b)=>a.period_end.localeCompare(b.period_end));const pts=rows.map(x=>({d:x.period_end,v:num(x.metric_value)}));return `<div class="card"><div class="res2-filterbar"><select onchange="res2MetricKey(this.value)">${keys.map(k=>`<option value="${k}" ${R.metricKey===k?'selected':''}>${safe(metricName(k))}</option>`).join('')}</select><div></div></div>${chart(pts)}</div><div class="card"><div class="res2-section-title"><b>Historial</b></div>${rows.length?rows.slice().reverse().map(x=>`<div class="res2-row"><div><b>${fmtDate(x.period_start)}–${fmtDate(x.period_end)}</b><small>${safe(x.source)} · ${qualityLabel(x.data_quality)}</small></div><div class="res2-value"><b>${valFormat(x.metric_key,x.metric_value,R.data.settings?.currency||'USD')}</b></div></div>`).join(''):'<div class="empty">No hay historial para esta métrica.</div>'}</div>`;}
  function chart(pts){if(pts.length<2)return'<div class="res2-chart-empty">Se necesitan al menos 2 puntos para mostrar tendencia.</div>';const w=600,h=180,p=18,min=Math.min(...pts.map(x=>x.v)),max=Math.max(...pts.map(x=>x.v)),range=max-min||1;const xy=pts.map((x,i)=>`${p+i*(w-2*p)/(pts.length-1)},${h-p-(x.v-min)*(h-2*p)/range}`).join(' ');return `<div class="res2-chart"><svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><polyline points="${xy}" fill="none" stroke="currentColor" stroke-width="3" vector-effect="non-scaling-stroke"></polyline>${pts.map((x,i)=>{const X=p+i*(w-2*p)/(pts.length-1),Y=h-p-(x.v-min)*(h-2*p)/range;return `<circle cx="${X}" cy="${Y}" r="4" fill="currentColor"></circle>`}).join('')}</svg></div>`;}

  function attribution(){return `<div class="card"><div class="res2-section-title"><b>Atribución de acciones</b></div><p class="hint">Relaciona temporalmente tareas, campañas, publicaciones y otras acciones con resultados. La interfaz no afirma causalidad cuando no puede demostrarse.</p>${topActions()}</div><div class="card"><div class="res2-section-title"><b>Publicaciones y piezas de contenido</b></div>${contentResults()}</div><div class="card"><div class="res2-section-title"><b>Competencia</b></div>${competitorResults()}</div>`;}
  function contentResults(){const cur=rowsFor(periodRange());const list=[];R.data.content.forEach(c=>(c.publications||[]).forEach(p=>{const m=cur.filter(x=>x.publication_id===p.id||x.content_item_id===c.id);list.push({c,p,sales:aggregate(m,'attributed_sales'),orders:aggregate(m,'orders'),reach:aggregate(m,'reach')||aggregate(m,'views')});}));list.sort((a,b)=>num(b.sales)-num(a.sales));return list.length?list.slice(0,20).map(x=>`<div class="res2-row"><div><b>${safe(x.c.title||x.c.content_type)} · ${safe(x.p.platform)}</b><small>${fmtDate(x.p.published_at||x.p.scheduled_at)} · ${safe(x.c.commercial_goal||'')}</small></div><div class="res2-value"><b>${x.sales!=null?money(x.sales,R.data.settings?.currency||'USD'):x.orders!=null?`${qty(x.orders)} pedidos`:x.reach!=null?`${qty(x.reach)} alcance`:'Sin datos'}</b></div></div>`).join(''):'<div class="empty">No hay publicaciones con métricas vinculadas.</div>';}
  function competitorResults(){const p=periodRange();if(!R.data.competitors.length)return'<div class="empty">No hay competidores cargados.</div>';return R.data.competitors.map(c=>{const m=R.data.competitorMetrics.filter(x=>x.competitor_id===c.id&&inRange(x,p));const rating=aggregate(m,'rating'),reviews=aggregate(m,'review_count'),newr=aggregate(m,'google_reviews_new');return `<div class="res2-row"><div><b>${safe(c.name)}</b><small>${safe(c.location||c.competitor_type)}</small></div><div class="res2-value"><b>${rating!=null?`${rating.toFixed(1)} ⭐`:'Sin rating'}</b><small>${reviews!=null?`${qty(reviews)} reseñas`:''}${newr!=null?` · +${qty(newr)}`:''}</small></div></div>`;}).join('');}

  function experiments(){return `<div class="card"><div class="res2-section-title"><b>Nueva prueba controlada</b></div><div class="form-grid"><div class="wide"><label class="field-label">Qué vamos a probar</label><input id="rExpName" placeholder="Ej: promoción martes 2x1"></div><div class="wide"><label class="field-label">Hipótesis</label><textarea id="rExpHyp" placeholder="Qué esperamos que cambie"></textarea></div><div><label class="field-label">Métrica principal</label><input id="rExpMetric" value="sales"></div><div><label class="field-label">Estado</label><select id="rExpStatus"><option value="planned">Planificada</option><option value="running">En curso</option></select></div><div><label class="field-label">Inicio baseline</label><input id="rExpB1" type="date"></div><div><label class="field-label">Fin baseline</label><input id="rExpB2" type="date"></div><div><label class="field-label">Inicio prueba</label><input id="rExpT1" type="date"></div><div><label class="field-label">Fin prueba</label><input id="rExpT2" type="date"></div></div><div class="res2-actions"><button class="btn primary" onclick="res2SaveExperiment()">Guardar prueba</button></div></div><div class="card"><div class="res2-section-title"><b>Experimentos</b></div>${R.data.experiments.length?R.data.experiments.map(x=>`<div class="res2-row"><div><b>${safe(x.name)}</b><small>${safe(x.primary_metric_key)} · ${safe(x.status)} · ${safe(x.decision||'sin decisión')}</small></div><div class="res2-value"><b>${x.change_percent!=null?pct(x.change_percent):'—'}</b></div></div>`).join(''):'<div class="empty">Todavía no hay pruebas.</div>'}</div>`;}

  function dataView(){const p=periodRange(),cur=rowsFor(p),required=['sales','avg_ticket','customers','direct_orders','google_actions','leads','reservations','reach','clicks','ad_spend','gross_profit','new_customers','returning_customers','cac','ltv'];const available=required.filter(k=>aggregate(cur,k)!=null),coverage=Math.round(available.length/required.length*100);const stale=R.data.systems.filter(s=>s.connection_status==='connected'&&!R.data.metrics.some(m=>m.source?.toLowerCase().includes(s.system_name.toLowerCase())&&m.last_synced_at&&dateInZone(m.last_synced_at)>=addDays(today(),-7)));return `<div class="card"><div class="res2-section-title"><b>Cobertura de medición · ${coverage}%</b></div><div class="res2-cover"><i style="width:${coverage}%"></i></div><div class="res2-statusline"><span>✅ ${available.length} disponibles</span><span>⚠️ ${required.length-available.length} faltantes</span></div>${required.filter(k=>!available.includes(k)).slice(0,8).map(k=>`<div class="res2-quality"><div><b>${metricName(k)}</b><small>Dato no disponible para el período.</small></div><span class="res2-pill warn">Falta dato</span></div>`).join('')}</div><div class="card"><div class="res2-section-title"><b>Fuentes y actualización</b></div>${R.data.systems.length?R.data.systems.map(s=>`<div class="res2-quality"><div><b>${safe(s.system_name)}</b><small>${safe(s.system_category)} · ${safe(s.connection_status)}</small></div><span class="res2-pill ${s.connection_status==='connected'?'ok':'warn'}">${s.connection_status==='connected'?'Automático posible':'Manual / sin conexión'}</span></div>`).join(''):'<div class="empty">No hay sistemas del cliente registrados.</div>'}${stale.length?`<div class="res2-alert medium"><b>⚠️ Hay conexiones sin datos recientes</b><small>${stale.map(x=>x.system_name).join(', ')}</small></div>`:''}</div><div class="card"><div class="res2-section-title"><b>Calidad de los datos</b></div>${['verified','estimated','client_reported','incomplete'].map(q=>`<div class="res2-quality"><div><b>${qualityLabel(q)}</b><small>${cur.filter(x=>x.data_quality===q).length} registros</small></div></div>`).join('')}</div><div class="card"><div class="res2-section-title"><b>Importación masiva</b></div><div class="res2-upload"><input id="res2File" type="file" accept=".csv,.xlsx,.xls" onchange="res2ReadFile(this.files[0])"><p class="hint">CSV o Excel. Se muestra una vista previa antes de guardar.</p></div><div id="res2ImportPreview"></div></div>`;}

  function askView(){return `<div class="res2-qa"><h2>Preguntar a Resultados</h2><p>Haz una pregunta sobre ventas, canales, productos, campañas o acciones. El análisis usa únicamente los datos disponibles del cliente.</p><textarea id="res2Question" placeholder="Ej: ¿por qué bajaron las ventas esta semana?"></textarea><div class="res2-actions"><button class="btn primary" onclick="res2Ask()">Analizar</button></div><div id="res2Answer"></div></div>`;}
  function clientView(){R.mode='client';const cur=rowsFor(periodRange()),prev=rowsFor(previousRange()),ins=insights(cur,prev).filter(x=>x.level==='good'),bad=insights(cur,prev).filter(x=>x.level!=='good');return `<div class="card"><div class="res2-section-title"><b>Resumen para el cliente</b><span class="res2-pill ok">Vista cliente</span></div><div class="res2-kpis">${['sales','direct_orders','google_reviews_new','google_actions'].map(k=>kpi(k,cur,prev)).join('')}</div></div><div class="card"><div class="res2-section-title"><b>Principales logros</b></div>${ins.length?ins.map(x=>`<div class="res2-alert good"><b>✅ ${safe(x.title)}</b><small>${safe(x.detail)}</small></div>`).join(''):'<div class="empty">Todavía no hay mejoras medibles suficientes.</div>'}</div><div class="card"><div class="res2-section-title"><b>Próximas acciones</b></div>${bad.length?bad.map(x=>`<div class="res2-row"><div><b>${safe(x.title)}</b><small>${safe(x.detail)}</small></div></div>`).join(''):'<div class="empty">No hay alertas críticas para el período.</div>'}</div><div class="res2-actions"><button class="btn ghost" onclick="res2InternalMode()">Volver a vista interna</button><button class="btn primary" onclick="res2GenerateReport()">Generar reporte</button></div>`;}

  function recordView(){const d=R.data;return `<div class="card"><div class="res2-section-title"><b>Registrar resultado</b></div><div class="form-grid"><div><label class="field-label">Métrica</label><input id="rKey" list="rMetricKeys" placeholder="sales"><datalist id="rMetricKeys">${Object.keys(MET).map(k=>`<option value="${k}">${MET[k].label}</option>`).join('')}</datalist></div><div><label class="field-label">Valor</label><input id="rValue" type="number" step="any"></div><div><label class="field-label">Fuente</label><input id="rSource" placeholder="POS, Google, Instagram…"></div><div><label class="field-label">Canal</label><select id="rChannel"><option value="">Sin canal</option>${['google','instagram','facebook','tiktok','web','whatsapp','orders','pos','delivery','other'].map(x=>`<option value="${x}">${channelLabel(x)}</option>`).join('')}</select></div><div><label class="field-label">Inicio</label><input id="rStart" type="date" value="${periodRange().start}"></div><div><label class="field-label">Fin</label><input id="rEnd" type="date" value="${periodRange().end}"></div><div><label class="field-label">Calidad</label><select id="rQuality"><option value="verified">Verificado</option><option value="estimated">Estimado</option><option value="client_reported">Reportado por cliente</option><option value="incomplete">Incompleto</option></select></div><div><label class="field-label">Método</label><select id="rMethod"><option value="manual">Manual</option><option value="import">Importación</option><option value="api">Automático / API</option></select></div><div><label class="field-label">Ubicación</label><select id="rLoc"><option value="">Todas</option>${d.locations.map(x=>`<option value="${x.id}">${safe(x.location_name||x.address)}</option>`).join('')}</select></div><div><label class="field-label">Producto</label><select id="rProduct"><option value="">Sin producto</option>${d.products.map(x=>`<option value="${x.id}">${safe(x.name)}</option>`).join('')}</select></div><div><label class="field-label">Campaña</label><select id="rCampaign"><option value="">Sin campaña</option>${d.campaigns.map(x=>`<option value="${x.id}">${safe(x.name)}</option>`).join('')}</select></div><div><label class="field-label">Es baseline</label><select id="rBaseline"><option value="false">No</option><option value="true">Sí</option></select></div></div><div class="res2-actions"><button class="btn primary" onclick="res2SaveMetric()">Guardar resultado</button><button class="btn ghost" onclick="res2Go('dashboard')">Cancelar</button></div></div>`;}

  async function renderMetrics(m){try{await ensure();if(!R.clientId){m.innerHTML=pageHead('Medición','📈 Resultados','Selecciona un cliente para trabajar con resultados.','<button class="btn ghost" onclick="openTool(\'home\')">← Inicio</button>')+chooser();return;}R.mode=R.view==='client'?'client':'internal';await loadData();let body='';if(R.view==='dashboard')body=dashboard();else if(R.view==='record')body=recordView();else if(R.view==='channels')body=channels();else if(R.view==='products')body=products();else if(R.view==='campaigns')body=campaigns();else if(R.view==='trends')body=trends();else if(R.view==='attribution')body=attribution();else if(R.view==='experiments')body=experiments();else if(R.view==='data')body=dataView();else if(R.view==='ask')body=askView();else if(R.view==='client')body=clientView();m.innerHTML=shell(body);}catch(e){console.error(e);workspaceError(m,e);}}

  window.res2Go=v=>{R.view=v;renderMetrics($('main'));};
  window.res2Period=v=>{R.period=v;if(v!=='custom')renderMetrics($('main'));else{R.customStart=addDays(today(),-29);R.customEnd=today();renderMetrics($('main'));}};
  window.res2ApplyCustom=()=>{R.customStart=$('res2Start').value;R.customEnd=$('res2End').value;if(!R.customStart||!R.customEnd)return toast('Completa las dos fechas');renderMetrics($('main'));};
  window.res2Location=v=>{R.locationId=v;renderMetrics($('main'));};
  window.res2MetricKey=v=>{R.metricKey=v;renderMetrics($('main'));};
  window.res2SelectClient=v=>{if(!v)return;setWorkspaceActiveClient(v);R.clientId=v;R.view='dashboard';renderMetrics($('main'));};
  window.res2InternalMode=()=>{R.mode='internal';R.view='dashboard';renderMetrics($('main'));};
  window.res2SaveMetric=async()=>{try{const key=$('rKey').value.trim(),value=Number($('rValue').value),start=$('rStart').value,end=$('rEnd').value;if(!key||!Number.isFinite(value)||!start||!end)throw new Error('Completa métrica, valor y período.');const row={client_id:R.clientId,location_id:$('rLoc').value||null,source:$('rSource').value.trim()||'Manual',metric_key:key,metric_value:value,period_start:start,period_end:end,is_baseline:$('rBaseline').value==='true',data_quality:$('rQuality').value,collection_method:$('rMethod').value,collection_frequency:collectionFrequency(start,end),channel:$('rChannel').value||null,metric_unit:MET[key]?.unit||null,product_id:$('rProduct').value||null,campaign_id:$('rCampaign').value||null,last_synced_at:$('rMethod').value==='api'?new Date().toISOString():null,metadata:{}};const{error}=await sb.from('metrics').insert(row);if(error)throw error;toast('Resultado guardado ✓');R.view='dashboard';renderMetrics($('main'));}catch(e){console.error(e);toast('Error: '+e.message);}};
  window.res2CreateTask=async(title,description)=>{try{const{error}=await sb.from('tasks').insert({client_id:R.clientId,title,description,priority:'high',expected_profit_impact:'high',status:'pending',task_type:'sales',origin:'results',origin_ref_type:'results_period',origin_ref_id:`${periodRange().start}_${periodRange().end}`});if(error)throw error;toast('Tarea creada desde Resultados ✓');}catch(e){toast('Error: '+e.message);}};
  window.res2SaveExperiment=async()=>{try{const name=$('rExpName').value.trim(),metric=$('rExpMetric').value.trim();if(!name||!metric)throw new Error('Completa nombre y métrica principal.');const row={client_id:R.clientId,name,hypothesis:$('rExpHyp').value.trim()||null,primary_metric_key:metric,status:$('rExpStatus').value,baseline_start:$('rExpB1').value||null,baseline_end:$('rExpB2').value||null,test_start:$('rExpT1').value||null,test_end:$('rExpT2').value||null};const{error}=await sb.from('result_experiments').insert(row);if(error)throw error;toast('Prueba guardada ✓');renderMetrics($('main'));}catch(e){toast('Error: '+e.message);}};
  window.res2GenerateReport=async()=>{try{const p=periodRange(),cur=rowsFor(p),prev=rowsFor(previousRange()),ins=insights(cur,prev),wins=ins.filter(x=>x.level==='good').map(x=>x.title),problems=ins.filter(x=>x.level!=='good').map(x=>x.title),summary=`Resultados ${fmtDate(p.start)}–${fmtDate(p.end)}. ${wins.length?wins.length+' mejoras detectadas.':'Sin mejoras concluyentes.'} ${problems.length?problems.length+' puntos requieren atención.':''}`;const metrics_summary={sales:aggregate(cur,'sales'),direct_orders:aggregate(cur,'direct_orders'),google_actions:aggregate(cur,'google_actions'),leads:aggregate(cur,'leads'),period:p};const{error}=await sb.from('reports').insert({client_id:R.clientId,report_type:'results_summary',period_start:p.start,period_end:p.end,executive_summary:summary,wins,problems,actions_completed:[],next_actions:problems,metrics_summary});if(error)throw error;toast('Reporte generado ✓');}catch(e){toast('Error: '+e.message);}};
  window.res2Ask=()=>{const q=$('res2Question').value.trim().toLowerCase(),cur=rowsFor(periodRange()),prev=rowsFor(previousRange());if(!q)return toast('Escribe una pregunta');let title='Conclusión',ans='No hay información suficiente para determinarlo con los datos actuales.';const response=(k)=>{const a=aggregate(cur,k),b=aggregate(prev,k),c=change(a,b);if(a==null)return null;return `${metricName(k)}: ${valFormat(k,a,R.data.settings?.currency||'USD')}${c==null?'':` (${pct(c)} vs período anterior)`}.`;};if(q.includes('venta')){const x=response('sales');if(x)ans=x+' '+(change(aggregate(cur,'sales'),aggregate(prev,'sales'))<0?'Conviene revisar canales, horarios y acciones del período.':'La tendencia del período es favorable.');}else if(q.includes('promoc')||q.includes('campañ')){const c=R.data.campaigns.map(z=>({z,v:aggregate(cur.filter(m=>m.campaign_id===z.id),'attributed_sales')})).filter(x=>x.v!=null).sort((a,b)=>b.v-a.v)[0];if(c)ans=`La campaña con mayor venta atribuible en el período es “${c.z.name}” con ${money(c.v,R.data.settings?.currency||'USD')}.`;}else if(q.includes('producto')||q.includes('plato')){const x=R.data.products.map(p=>({p,v:aggregate(cur.filter(m=>m.product_id===p.id),'sales')||aggregate(cur.filter(m=>m.product_id===p.id),'attributed_sales')})).filter(x=>x.v!=null).sort((a,b)=>b.v-a.v)[0];if(x)ans=`El producto con mayor venta medida en el período es “${x.p.name}” con ${money(x.v,R.data.settings?.currency||'USD')}.`;}else if(q.includes('instagram')){const rows=cur.filter(x=>(x.channel||inferChannel(x.source))==='instagram'),reach=aggregate(rows,'reach')||aggregate(rows,'views'),orders=aggregate(rows,'orders')||aggregate(rows,'direct_orders');if(reach!=null||orders!=null)ans=`Instagram: ${reach!=null?qty(reach)+' de alcance/reproducciones. ':''}${orders!=null?qty(orders)+' pedidos atribuibles.':''}`;}else if(q.includes('impacto')||q.includes('acción')){const a=(R.data.attributions||[]).slice().sort((x,y)=>num(y.attributed_revenue||y.attributed_value)-num(x.attributed_revenue||x.attributed_value))[0];if(a)ans=`La acción con mayor impacto atribuido registrado es ${a.source_type}${a.notes?' · '+a.notes:''}, con ${a.attributed_revenue!=null?money(a.attributed_revenue,R.data.settings?.currency||'USD'):qty(a.attributed_value)}.`;}$('res2Answer').innerHTML=`<div class="res2-answer"><b>${title}</b><br>${safe(ans)}</div>`;};

  window.res2ReadFile=async file=>{if(!file)return;R.importFile=file;try{const ext=file.name.split('.').pop().toLowerCase();let rows=[];if(ext==='csv'){rows=parseCSV(await file.text());}else{await loadXLSX();const buf=await file.arrayBuffer(),wb=XLSX.read(buf),ws=wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json(ws,{defval:''});}R.importRows=rows;renderImportPreview(rows,file.name);}catch(e){console.error(e);toast('No se pudo leer el archivo');}};
  function parseCSV(t){const lines=t.split(/\r?\n/).filter(Boolean),heads=(lines.shift()||'').split(',').map(x=>x.trim().replace(/^"|"$/g,''));return lines.map(line=>{const vals=line.match(/("[^"]*(?:""[^"]*)*"|[^,]*)/g)?.filter((_,i)=>i%2===0).map(x=>x.replace(/^"|"$/g,'').replaceAll('""','"'))||line.split(',');const o={};heads.forEach((h,i)=>o[h]=vals[i]??'');return o;});}
  function loadXLSX(){if(window.XLSX)return Promise.resolve();return new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=res;s.onerror=()=>rej(new Error('No se pudo cargar lector Excel'));document.head.appendChild(s);});}
  function renderImportPreview(rows,name){const h=$('res2ImportPreview');if(!h)return;const cols=rows.length?Object.keys(rows[0]):[];h.innerHTML=`<div class="res2-import-preview"><table class="res2-table"><thead><tr>${cols.map(c=>`<th>${safe(c)}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,8).map(r=>`<tr>${cols.map(c=>`<td>${safe(r[c])}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="hint">${rows.length} filas detectadas en ${safe(name)}. Para importar automáticamente, las columnas recomendadas son: metric_key, metric_value, period_start, period_end, source, channel, data_quality.</p><button class="btn primary" onclick="res2ConfirmImport()">Confirmar importación</button>`;}
  window.res2ConfirmImport=async()=>{try{if(!R.importRows.length)throw new Error('No hay filas para importar.');const valid=[],errors=[];for(let i=0;i<R.importRows.length;i++){const r=R.importRows[i],key=String(r.metric_key||r.metric||r.metrica||'').trim(),value=Number(r.metric_value??r.value??r.valor),start=String(r.period_start||r.start||r.fecha||'').slice(0,10),end=String(r.period_end||r.end||r.fecha||'').slice(0,10);if(!key||!Number.isFinite(value)||!start){errors.push({row:i+2,error:'Faltan métrica, valor o fecha'});continue;}valid.push({client_id:R.clientId,source:r.source||r.fuente||'Importación',metric_key:key,metric_value:value,period_start:start,period_end:end||start,data_quality:r.data_quality||'verified',collection_method:'import',collection_frequency:r.collection_frequency||collectionFrequency(start,end||start),channel:r.channel||null,metric_unit:MET[key]?.unit||null,metadata:{import_file:R.importFile?.name||''}});}if(valid.length){for(let i=0;i<valid.length;i+=500){const{error}=await sb.from('metrics').insert(valid.slice(i,i+500));if(error)throw error;}}await sb.from('result_imports').insert({client_id:R.clientId,file_name:R.importFile?.name||'archivo',file_type:R.importFile?.name?.split('.').pop()||null,source:'file_import',status:'completed',rows_total:R.importRows.length,rows_imported:valid.length,rows_skipped:errors.length,errors,completed_at:new Date().toISOString()});toast(`Importados ${valid.length} registros ✓`);R.importRows=[];R.importFile=null;renderMetrics($('main'));}catch(e){console.error(e);toast('Error: '+e.message);}};

  window.renderMetrics=renderMetrics;
})();
